### ISSUE TITLE
Issues with Object Comparison

### ISSUE THREAD

**Issue by swachtma** [levinmr/rspec-snapshot#5]
I'm having some tests come back as failures despite reporting that would seem to indicate otherwise.

For example:
```
  1) AuthToken decodes valid tokens
     Failure/Error: expect(AuthToken.decode(@token)).to match_snapshot("controllers/concerns/auth_token_decode")

       expected: {"user_id"=>1}
            got: {"user_id"=>1}
     # ./spec/api/controllers/concerns/auth_token_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:68:in `block (2 levels) in <top (required)>'
```
Coming off the following tests:

```
require 'rails_helper'

RSpec.describe AuthToken, :type => :request do
  before(:example) do
    @token = AuthToken.encode({user_id: 1},9999)
  end
  
  it "creates new tokens" do
    expect(@token).to match_snapshot("controllers/concerns/auth_token_encode")
  end
  
  it "decodes valid tokens" do
    expect(AuthToken.decode(@token)).to match_snapshot("controllers/concerns/auth_token_decode")
  end
end

It seems like the comparison of objects might be expecting the referential equality?  But I'm not sure why these tests fail when other tests looking at similar responses pass.

```

**Edit:** wrapping the snapshot expectation in JSON.generate resolves this issue.

**Comment by rrcobb** [comment]
#8 switches the serialization library, and might make some of these kinds of problems go away

**Comment by levinmr** [comment]
Please check if this is still an issue in the current 2.0.0 release.  Thanks
